---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  ports:
  - name: admin-service-http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: moop
    service: admin-service
  type: ClusterIP
