---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-service-config

data:
    config.py: |-
      HOST = '0.0.0.0'
      PORT = 80
      DEBUG = False
      MONGODB_URI='mongodb://mongodb.database.svc:27017'
      MONGODB_NAME='MOOP_STATUS'